export const PREDEFINED_COLORS = [
  { value: '#0000FF', label: 'Blau' },
  { value: '#000080', label: 'Marine' },
  { value: '#00FF00', label: 'Grün' },
  { value: '#00FFFF', label: 'Cyan' },
  { value: '#20B2AA', label: 'Türkis' },
  { value: '#32CD32', label: 'Limette' },
  { value: '#48D1CC', label: 'Aquamarin' },
  { value: '#4B0082', label: 'Indigo' },
  { value: '#7B68EE', label: 'Mittellila' },
  { value: '#800080', label: 'Lila' },
  { value: '#8B4513', label: 'Braun' },
  { value: '#FF0000', label: 'Rot' },
  { value: '#FF00FF', label: 'Pink' },
  { value: '#FF1493', label: 'Pink' },
  { value: '#FF4500', label: 'Orange-Rot' },
  { value: '#FF69B4', label: 'Rosa' },
  { value: '#FFA500', label: 'Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFF00', label: 'Gelb' },
  { value: '#008000', label: 'Dunkelgrün' }
].sort((a, b) => a.value.localeCompare(b.value))
